services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: mind-student
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true